sudo: required

services:
  - docker

script:
  - docker build -t dust-calculator .
  - docker tag dust-calculator quay.io/ian/dust-calculator
  - docker login quay.io -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD"
  - docker push quay.io/ian/dust-calculator
